### ISSUE TITLE
How to download pretrained models

### ISSUE THREAD

**Issue by yoolern10** [LoYuXr/CalliRewrite#4]
Hello! I'd like to know how to download the pretrained models for your CalliRewrite project. I don't think it's explained in the page.

Thanks.

**Comment by LoYuXr** [comment]
we will release the two-stage fine-tuning models. please put them in outputs/snapshot/new_train_phase_1 and new_train_phase_2 separately.

**Comment by yoolern10** [comment]
Thank you. Around when do you think would be the release of these models?

**Comment by LoYuXr** [comment]
please wait for another 10 minutes LOL
