### ISSUE TITLE
Extracting Coarse Sequences

### ISSUE THREAD

**Issue by awei669** [LoYuXr/CalliRewrite#5]
作者您好，这项工作非常有趣，我有一个问题：在生成笔划粗序列时，参数W0和W1是如何控制贝塞尔曲线的粗细的，有相关的资料参考一下么？

**Comment by LoYuXr** [comment]
您好。我们的笔画无监督提取模块主要基于siggraph 2021 general virtual sketching frameowrk (link: https://github.com/MarkMoHR/virtual_sketching) 开发。其中0, y0, x1, y1, x2, y2, z0, z2, w0, w2 = f, 两个widths 是lstm的输出预测笔画起终点的粗细。中间使用线性差值进行处理。由于width的引入使得模型可以不仅处理sketch，还可以泛化到笔画粗细不均匀的艺术字上，达到更好的重绘效果。
如果您希望follow我们的工作或者寻求进一步的开发合作，也欢迎邮件联系。

**Comment by awei669** [comment]
了解您的意思了，在序列笔划生成过程中考虑stroke粗细这个因素是个很好的启发。

非常感谢作者及时的回复，希望未来有机会可以跟贵组交流合作。（论文和github上貌似没找到您的邮箱ovo。

**Comment by LoYuXr** [comment]
通讯作者是连宙辉老师，邮箱lianzhouhui@pku.edu.cn. 我的邮箱 2000017426@stu.pku.edu.cn
