### ISSUE TITLE
Some issues

### ISSUE THREAD

**Issue by awei669** [LoYuXr/CalliRewrite#6]
1. seq_extract/hyper_parameters.py 文件缺少方法 get_default_hparams_clean()
2. 推理时需要下载以下权重：
```
outputs/
    snapshot/
        pretrain_neural_renderer/
        pretrain_perceptual_model/
```
seq_extract/test_vectorization.py文件 441行
load_checkpoint(sess, 'outputs/snapshot/pretrain_perceptual_model', perceptual_only=True)的模型路径需要修改。
3. 我在推理时输出的笔画序列为空，strokes_raw_out_list=[[]]，模型应该是正确加载了，暂时不清楚哪里出了问题。
![图片](https://github.com/user-attachments/assets/e2a78c39-07bf-44b4-a077-ff5f9041c2a3)

**Comment by LoYuXr** [comment]
1. 将test_vectorization  line 414 代码替换成：model_params_default = hparams.get_default_hparams_phase_2() 之后可运行
python ./test.py --input img_dir --model new_train_phase_2

2. 请参考GVS工作下载对应的VGG-16等参数。
3. 经过上面的改错，本地测试是可以inference的

**Comment by awei669** [comment]
推理时--inputs指定为 `CalliRewrite/seq_extract/sample_inputs` 导致出错，已解决。
